# What is API?
API  : API stands for Application Programming Interface which allows software applications to communicate with each other via API calls.


#  What are the main HTTP Methods?
GET       ==> Used to get information from web server
POST      ==> Used to create new record in web server
PUT       ==> used to update existing record in web server
DELETE    ==> Used to remove record in web servers



# EXAMPLE
AMAZON ==> Phonepay -- C 
           Gpay     -- JAVA
           paytm    -- PYTHON
           SBI
           HDFC
           CITI
           ICICI

D = {BANK NAME : SBI
    CARD NAME : SRIRAM
    CARD NUMBER : 854837
    CVV      : 345
    AMOUNT   : 1000
    EXP DATE : 2345
    }

D = {OTP:3456}



## Follow Below steps to do API testing 

    # 1. Install Below two required modules using below commands
        python -m pip install flask
        python -m pip install requests


    # 2. Run Flask script like below then " don't close command prompt "
        python 1_server_side_script_flask.py


